#!/bin/bash

# A *Pre-* Program for Graphic Design
# A *New* Program for Graphic Design

# Package .epub flavors 
# (Apple, Library Stack, O-R-G)
# from clean indesign .epub exports 
# replacing existing files

# ** important ** 
# always run this script outside of icloud drive
# or will trigger icloud update of all files

# usage: ./__make path/to/in path/to/out

LOG=log.txt
ERROR=error.txt
IN=$1
OUT=$2
# Apple 
# AUDIO_ONLY=-a

# begin

echo "** important **"
echo "Always run this script outside of icloud drive"
echo "or will trigger icloud update of all files."

echo "Are you running this script outside of icloud [y/n] ?"
read ICLOUD
if [[ $ICLOUD != "y" ]]
then
    echo "Please mv * to a static location -- exiting ..."
    exit
else 
   echo "OK -- starting ..."
fi

echo "**
echo `date` > $LOG
echo `date` > $ERROR
echo `date`" 
echo -e "\n\n\n"

FILE='A New Program for Graphic Design.epub'
if test -f "$IN/$FILE"
then
    echo -e "<-- $IN/$FILE"
    ./__validate "$IN/$FILE" 2>>$ERROR
    mv validate.epub "$OUT/$FILE"
    echo -e "--> $OUT/$FILE \n\n\n"
fi

FILE='A New Program for Graphic Design sample.epub'
if test -f "$IN/$FILE"
then
    echo -e "<-- $IN/$FILE"
    ./__validate "$IN/$FILE" 2>>$ERROR
    mv validate.epub "$OUT/$FILE"
    echo -e "--> $OUT/$FILE \n\n\n"
fi

FILE='A Pre- Program for Graphic Design.epub'
if test -f "$IN/$FILE"
then
    echo -e "<-- $IN/$FILE"
    ./__package "$IN/$FILE" $AUDIO_ONLY 1>>$LOG
    ./__validate package.epub 2>>$ERROR
    mv validate.epub "$OUT/$FILE"
    echo -e "--> $OUT/$FILE \n\n\n"
fi

FILE='A Pre- Program for Graphic Design sample.epub'
if test -f "$IN/$FILE"
then
    echo -e "<-- $IN/$FILE"
    ./__package "$IN/$FILE" $AUDIO_ONLY 1>>$LOG
    ./__validate package.epub 2>>$ERROR
    mv validate.epub "$OUT/$FILE"
    echo -e "--> $OUT/$FILE \n\n\n"
fi

# end

echo "--> $IN"
ls "$IN"
echo -e "\n"
echo "--> $OUT"
ls "$OUT"
echo -e "\n"

echo "Cleanup $IN [y/n] ?"
read CLEANUP
if [[ $CLEANUP == "y" ]]
then
   rm $IN/*
    echo "Deleted $IN/*"
else 
   echo "Leaving $IN/*"
fi

echo "done."
